[package]
name = "md5sum"
version = "0.1.0"
edition = "2021"
authors = ["Your Name"]
description = "A command line tool to compute and check MD5 checksums"

[dependencies]
md-5 = "0.10.6"
clap = { version = "4.5.21", features = ["derive"] }
anyhow = "1.0.93"
