name: Release

on:
  push:
    tags:
      - 'v*'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      
      - name: Install latest rust toolchain
        uses: dtolnay/rust-toolchain@stable
        
      - name: Build
        run: cargo build --release
        
      - name: Run tests
        run: cargo test --release
        
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: ./target/release/md5sum.exe
          draft: false
          prerelease: false
          generate_release_notes: true
